services:
  tuya-api:
    image: denoland/deno:2.6.9
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DENO_DIR=/app/.deno
    ports:
      - "8000:8000"
    command: ["deno", "task", "start"]
